# Generated by Django 4.2.7 on 2024-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_name1_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name1',
        ),
        migrations.AddField(
            model_name='product',
            name='name_template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
