# Generated by Django 4.2.7 on 2024-03-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_name1_product_name_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_template', models.TextField(default='Unknown')),
                ('description', models.TextField(default='')),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('characteristics', models.TextField(default='')),
                ('display', models.TextField(default='Unknown')),
                ('cpu', models.TextField(default='Unknown')),
                ('camera', models.TextField(default='')),
                ('battery', models.TextField(default='')),
                ('size', models.TextField(default='Unknown')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='AdditionalImageLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.laptop')),
            ],
        ),
    ]
