# Generated by Django 4.2.7 on 2024-03-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_laptop_alter_product_name_additionalimagelaptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_template', models.TextField(default='Unknown')),
                ('description', models.TextField(default='')),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('characteristics', models.TextField(default='')),
                ('cpu', models.TextField(default='Unknown')),
                ('display', models.TextField(default='Unknown')),
                ('information', models.TextField(default='')),
                ('size', models.TextField(default='Unknown')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AdditionalImagePlayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
                ('PlayStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.playstation')),
            ],
        ),
    ]
