# Generated by Django 4.2.7 on 2024-03-31 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_playstation_alter_laptop_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_template', models.TextField(default='Unknown')),
                ('description', models.TextField(default='')),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('characteristics', models.TextField(default='')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImageSmallProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
                ('SmallProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.smallproduct')),
            ],
        ),
    ]
